
# playlist_files:
#   - file: config/playlists.yml
#   - git: meisnate12/Playlists
libraries:                                      # Library mappings must have a colon (:) placed after them
  # Movies:
  #   metadata_path:
  #     - file: config/movies/genre.yml
  #     - file: config/movies/studios.yml
  #     - file: config/movies/movies.yml
  #   settings:
  #     asset_directory: config/assets/movies/
  TV Shows:
    metadata_path:
      - file: config/tvshows/networks.yml
    settings:
      asset_directory: config/assets/tvshows/
settings:                                       # Can be individually specified per library as well
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 5
  create_asset_folders: true
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  sync_mode: append
  minimum_items: 2
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: true
  save_missing: true
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  playlist_sync_to_user: all
  verify_ssl: true
webhooks:                                       # Can be individually specified per library as well
  error:
  run_start:
  run_end:
  changes:
plex:                                           # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://192.168.1.102:32400
  token: 
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:                                           # REQUIRED for the script to run
  apikey: 
  language: en
omdb:
  apikey: 
trakt:
  client_id: 
  client_secret: 
  authorization:
    access_token: 
    token_type: 
    expires_in: 
    refresh_token:
    scope: public
    created_at: 
